# Generated by Django 4.2.6 on 2023-10-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapImg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=300)),
                ('User_phone', models.BigIntegerField()),
                ('User_address', models.TextField()),
                ('User_pic', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
