# Generated by Django 4.2.6 on 2023-10-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swapImg', '0004_capturedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swapImg.userinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='CapturedImage',
        ),
    ]
